name: Sick Swallow
favicon: null
layout_spectrum: 0.25933
typography_spectrum: 0.34484
title: Sick Swallow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a2a39e'
    - '#0f2c6e'
    - '#aa8f24'
    - '#781300'
    - '#4b5c88'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
